# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import showcollection_pb2 as showcollection__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in showcollection_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ShowCollectionServiceStub(object):
    """define the service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendShowCollection = channel.unary_unary(
                '/showcollectionservice.ShowCollectionService/SendShowCollection',
                request_serializer=showcollection__pb2.ShowCollectionRequest.SerializeToString,
                response_deserializer=showcollection__pb2.ShowCollectionResponse.FromString,
                _registered_method=True)


class ShowCollectionServiceServicer(object):
    """define the service
    """

    def SendShowCollection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShowCollectionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendShowCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.SendShowCollection,
                    request_deserializer=showcollection__pb2.ShowCollectionRequest.FromString,
                    response_serializer=showcollection__pb2.ShowCollectionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'showcollectionservice.ShowCollectionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('showcollectionservice.ShowCollectionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ShowCollectionService(object):
    """define the service
    """

    @staticmethod
    def SendShowCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/showcollectionservice.ShowCollectionService/SendShowCollection',
            showcollection__pb2.ShowCollectionRequest.SerializeToString,
            showcollection__pb2.ShowCollectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
