# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: showcollection.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'showcollection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14showcollection.proto\x12\x15showcollectionservice\")\n\x15ShowCollectionRequest\x12\x10\n\x08showslug\x18\x01 \x01(\t\"9\n\x16ShowCollectionResponse\x12\x0e\n\x06showid\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x32\x8c\x01\n\x15ShowCollectionService\x12s\n\x12SendShowCollection\x12,.showcollectionservice.ShowCollectionRequest\x1a-.showcollectionservice.ShowCollectionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'showcollection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SHOWCOLLECTIONREQUEST']._serialized_start=47
  _globals['_SHOWCOLLECTIONREQUEST']._serialized_end=88
  _globals['_SHOWCOLLECTIONRESPONSE']._serialized_start=90
  _globals['_SHOWCOLLECTIONRESPONSE']._serialized_end=147
  _globals['_SHOWCOLLECTIONSERVICE']._serialized_start=150
  _globals['_SHOWCOLLECTIONSERVICE']._serialized_end=290
# @@protoc_insertion_point(module_scope)
