services:
  cfgsvr1:
    container_name: cfgsvr1
    image: mongo:latest
    command: mongod --configsvr --replSet cfgrs --port 27017 --bind_ip_all
    volumes:
      - cfgsvr1:/data/db
    networks:
      - mongocluster

  cfgsvr2:
    container_name: cfgsvr2
    image: mongo:latest
    command: mongod --configsvr --replSet cfgrs --port 27017 --bind_ip_all
    volumes:
      - cfgsvr2:/data/db
    networks:
      - mongocluster

  cfgsvr3:
    container_name: cfgsvr3
    image: mongo:latest
    command: mongod --configsvr --replSet cfgrs --port 27017 --bind_ip_all
    volumes:
      - cfgsvr3:/data/db
    networks:
      - mongocluster

  shard1svr1:
    container_name: shard1svr1
    image: mongo:latest
    command: mongod --shardsvr --replSet shard1rs --port 27017 --bind_ip_all
    volumes:
      - shard1svr1:/data/db
    networks:
      - mongocluster

  shard1svr2:
    container_name: shard1svr2
    image: mongo:latest
    command: mongod --shardsvr --replSet shard1rs --port 27017 --bind_ip_all
    volumes:
      - shard1svr2:/data/db
    networks:
      - mongocluster

  shard1svr3:
    container_name: shard1svr3
    image: mongo:latest
    command: mongod --shardsvr --replSet shard1rs --port 27017 --bind_ip_all
    volumes:
      - shard1svr3:/data/db
    networks:
      - mongocluster

  mongos:
    container_name: mongos
    image: mongo:latest
    command: mongos --configdb cfgrs/cfgsvr1:27017,cfgsvr2:27017,cfgsvr3:27017 --bind_ip_all --port 27017
    ports:
      - "27017:27017"
    networks:
      - mongocluster
    depends_on:
      - cfgsvr1
      - cfgsvr2
      - cfgsvr3
      - shard1svr1
      - shard1svr2
      - shard1svr3

volumes:
  cfgsvr1:
  cfgsvr2:
  cfgsvr3:
  shard1svr1:
  shard1svr2:
  shard1svr3:

networks:
  mongocluster:
    name: mongocluster
    driver: bridge
