# compose.yaml
services:
  # Single Config Server
  cfgsvr1:
    container_name: cfgsvr1
    image: mongo:latest
    command: mongod --configsvr --replSet cfgrs --port 27017 --bind_ip_all
    volumes:
      - cfgsvr1:/data/db
    networks:
      - mongocluster

  # Single Shard Server
  shard1svr1:
    container_name: shard1svr1
    image: mongo:latest
    command: mongod --shardsvr --replSet shard1rs --port 27017 --bind_ip_all
    volumes:
      - shard1svr1:/data/db
    networks:
      - mongocluster

  # Router
  mongos:
    container_name: mongos
    image: mongo:latest
    command: mongos --configdb cfgrs/cfgsvr1:27017 --bind_ip_all --port 27017
    ports:
      - "27017:27017"
    networks:
      - mongocluster
    depends_on:
      - cfgsvr1
      - shard1svr1

networks:
  mongocluster:
    driver: bridge

volumes:
  cfgsvr1:
  shard1svr1: